impl(language): unexport unnecessary fields
Unexport fields that do not need to be accessed outside of the language
package. This revealed several `staticcheck` and `unparam` errors, which
are now fixed.

--- FAIL: TestStaticCheck (1.55s)
        internal/language/golang.go:222:19: func (*goCodec).fqEnumValueName is unused (U1000)
--- FAIL: TestUnparam (1.17s)
        internal/language/golang.go:190:47: (*goCodec).messageName - state is unused
        internal/language/golang.go:230:47: (*goCodec).bodyAccessor - state is unused
        internal/language/golang.go:238:48: (*goCodec).httpPathFmt - state is unused
        internal/language/golang.go:252:49: (*goCodec).httpPathArgs - state is unused
        internal/language/rust.go:512:52: (*rustCodec).asQueryParameter - state is unused
        internal/language/rust.go:587:49: (*rustCodec).messageName - state is unused
        internal/language/rust.go:609:43: (*rustCodec).enumName - state is unused
        internal/language/rust.go:631:49: (*rustCodec).bodyAccessor - state is unused
        internal/language/rust.go:639:50: (*rustCodec).httpPathFmt - state is unused
        internal/language/rust.go:696:51: (*rustCodec).httpPathArgs - state is unused